query Pages_Profile_Edit_Index {
  viewer {
    name
    imageUrl
  }
}

mutation Pages_Profile_Edit($input: ProfileEditInput!) {
  profileEdit(input: $input) {
    user {
      name
      bio
      imageUrl
    }
    errors
  }
}
