query Pages_Posts_Index($limit: Int, $offset: Int) {
  viewer {
    ...Pages_Posts_User
  }
  posts(limit: $limit, offset: $offset) {
    ...Pages_Posts_Post
  }
  totalPosts
}

fragment Pages_Posts_User on User {
  name
  email
}

fragment Pages_Posts_Post on Post {
  title
  body
  imageUrl
  isPublished
  uid
  favoritesCount
  user {
    name
  }
  createdAt
  updatedAt
}

mutation Pages_Posts_Sort(
  $sortBy: String!
  $order: String!
  $limit: Int
  $offset: Int
) {
  postSort(
    input: { sortBy: $sortBy, order: $order, limit: $limit, offset: $offset }
  ) {
    posts {
      ...Pages_Posts_Post
    }
  }
}
