query Pages_Dashboard_Index {
  viewer {
    ...Pages_Dashboard_User
  }
  myPosts {
    ...Pages_Dashboard_Post
  }
}

fragment Pages_Dashboard_User on User {
  id
  email
  name
}

fragment Pages_Dashboard_Post on Post {
  title
  body
  imageUrl
  isPublished
  uid
  favoritesCount
  user {
    name
  }
  createdAt
}
