query Pages_Dashboard_Index($limit: Int, $offset: Int) {
  viewer {
    ...Pages_Dashboard_User
  }
  myposts(limit: $limit, offset: $offset) {
    ...Pages_Dashboard_Post
  }
}

fragment Pages_Dashboard_User on User {
  id
  name
  imageUrl
}

fragment Pages_Dashboard_Post on Post {
  title
  body
  imageUrl
  isPublished
  uid
  favoritesCount
  user {
    name
  }
  createdAt
  updatedAt
}

mutation Pages_Dashboard_myposts_Sort(
  $sortBy: String!
  $order: String!
  $limit: Int
  $offset: Int
) {
  mypostSort(
    input: { sortBy: $sortBy, order: $order, limit: $limit, offset: $offset }
  ) {
    myposts {
      ...Pages_Posts_Post
    }
  }
}
