query Pages_Post_Edit_Index {
  viewer {
    name
    imageUrl
  }
}

mutation Pages_Post_Edit($input: PostEditInput!) {
  postEdit(input: $input) {
    post {
      title
      body
      imageUrl
      isPublished
      uid
    }
    errors
  }
}
