query Pages_Post_Detail_Index($uid: String!, $name: String!) {
  viewer {
    ...Pages_Post_Detail_User
  }
  postDetail(uid: $uid, name: $name) {
    ...Pages_Post_Detail
  }
}
fragment Pages_Post_Detail on Post {
  id
  title
  body
  imageUrl
  isPublished
  uid
  favorited
  favoritesCount
  user {
    name
  }
  createdAt
}

fragment Pages_Post_Detail_User on User {
  name
  imageUrl
}
