name: Frontend CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run format
        run: npm run format

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Storybook
        run: npm run storybook
      - name: Run Storybook tests
        run: npm run test-storybook
