# name: E2E Playwright Dev Tests

# on:
#   workflow_call:

# jobs:
#   playwright-dev:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           repository: masahiro96848/dev-post-backend
#           path: dev-post-backend
#       - uses: docker/setup-buildx-action@v2
#       - uses: docker/build-push-action@v4
#         with:
#           context: ./dev-post-backend
#           file: ./dev-post-backend/rails/Dockerfile
#           load: true
#       - name: run dev-post-backend
#         run: |
#           chmod -R 777 .
#           docker compose up -d
#           docker compose exec rails rails db:seed
#           docker compose up -d

#         working-directory: rails
