name: E2E Playwright Dev Tests

on:
  workflow_call:

jobs:
  playwright-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # バックエンドのコードをチェックアウト
      - name: Checkout Backend Code
        uses: actions/checkout@v4
        with:
          repository: masahiro96848/dev-post-backend
          path: dev-post-backend

      # Docker Buildx のセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # バックエンドの Docker イメージをビルド
      - name: Build Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./dev-post-backend/rails
          file: ./dev-post-backend/rails/Dockerfile
          load: true

      # Docker コンテナの起動とデータベースのシード実行
      - name: Start Backend Services
        run: |
          docker compose up -d
          docker compose exec rails rails db:migrate
          docker compose exec rails rails db:seed
        working-directory: dev-post-backend

      # フロントエンドのコードをチェックアウト
      - name: Checkout Frontend Code
        uses: actions/checkout@v4
        with:
          path: dev-post-frontend

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # フロントエンドの依存関係をインストール
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: dev-post-frontend

      # Playwright のインストール
      - name: Install Playwright
        run: npx playwright install --with-deps
        working-directory: dev-post-frontend

      # フロントエンドをビルド
      - name: Build Frontend
        run: npm run build
        working-directory: dev-post-frontend

      # Playwright テストの実行
      - name: Run Playwright Tests
        run: npm run test-playwright
        working-directory: dev-post-frontend

      # Playwright レポートのアップロード
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: dev-post-frontend/playwright-report/
          retention-days: 30
